"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import addnn.controller.proto.controller_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Report(google.protobuf.message.Message):
    """Reporting information of a single scheduler run."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    START_TIMESTAMP_FIELD_NUMBER: builtins.int
    END_TIMESTAMP_FIELD_NUMBER: builtins.int
    NODES_FIELD_NUMBER: builtins.int
    PLACEMENT_FIELD_NUMBER: builtins.int
    ESTIMATED_LATENCY_FIELD_NUMBER: builtins.int
    ACTIVATION_DURATIONS_FIELD_NUMBER: builtins.int
    LAYER_PROFILES_FIELD_NUMBER: builtins.int
    start_timestamp: builtins.int = ...
    """The time at which the scheduler run was triggered (unix time in micro seconds)."""

    end_timestamp: builtins.int = ...
    """The time at which the scheduler run finished (unix time in micro seconds)."""

    @property
    def nodes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[addnn.controller.proto.controller_pb2.RegisteredNode]:
        """The nodes and their states that were considered during this scheduler run."""
        pass
    @property
    def placement(self) -> global___Placement:
        """The placement decision of this scheduler run."""
        pass
    estimated_latency: builtins.float = ...
    """The estimated end-to-end inference latency of the chosen placement."""

    @property
    def activation_durations(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """Activation duration per node that was part of the placement."""
        pass
    @property
    def layer_profiles(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LayerProfile]:
        """The profiles of the layers."""
        pass
    def __init__(self,
        *,
        start_timestamp : builtins.int = ...,
        end_timestamp : builtins.int = ...,
        nodes : typing.Optional[typing.Iterable[addnn.controller.proto.controller_pb2.RegisteredNode]] = ...,
        placement : typing.Optional[global___Placement] = ...,
        estimated_latency : builtins.float = ...,
        activation_durations : typing.Optional[typing.Iterable[builtins.int]] = ...,
        layer_profiles : typing.Optional[typing.Iterable[global___LayerProfile]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"placement",b"placement"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"activation_durations",b"activation_durations",u"end_timestamp",b"end_timestamp",u"estimated_latency",b"estimated_latency",u"layer_profiles",b"layer_profiles",u"nodes",b"nodes",u"placement",b"placement",u"start_timestamp",b"start_timestamp"]) -> None: ...
global___Report = Report

class Placement(google.protobuf.message.Message):
    """Represents a placement decision of a scheduler run."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NODES_FIELD_NUMBER: builtins.int
    @property
    def nodes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]:
        """For each layer this array holds the UUID of the respective node that was assigned to the layer."""
        pass
    def __init__(self,
        *,
        nodes : typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"nodes",b"nodes"]) -> None: ...
global___Placement = Placement

class LayerProfile(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    FLOPS_FIELD_NUMBER: builtins.int
    IN_MEMORY_SIZE_FIELD_NUMBER: builtins.int
    STORAGE_SIZE_FIELD_NUMBER: builtins.int
    MARSHALLED_INPUT_SIZE_FIELD_NUMBER: builtins.int
    HAS_EXIT_FIELD_NUMBER: builtins.int
    NUMBER_OF_EXITED_SAMPLES_FIELD_NUMBER: builtins.int
    EXIT_PROBABILITY_FIELD_NUMBER: builtins.int
    EXECUTION_PROBABILITY_FIELD_NUMBER: builtins.int
    OPERATORS_FIELD_NUMBER: builtins.int
    flops: builtins.int = ...
    in_memory_size: builtins.int = ...
    storage_size: builtins.int = ...
    marshalled_input_size: builtins.int = ...
    has_exit: builtins.bool = ...
    number_of_exited_samples: builtins.int = ...
    exit_probability: builtins.float = ...
    execution_probability: builtins.float = ...
    @property
    def operators(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    def __init__(self,
        *,
        flops : builtins.int = ...,
        in_memory_size : builtins.int = ...,
        storage_size : builtins.int = ...,
        marshalled_input_size : builtins.int = ...,
        has_exit : builtins.bool = ...,
        number_of_exited_samples : builtins.int = ...,
        exit_probability : builtins.float = ...,
        execution_probability : builtins.float = ...,
        operators : typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"execution_probability",b"execution_probability",u"exit_probability",b"exit_probability",u"flops",b"flops",u"has_exit",b"has_exit",u"in_memory_size",b"in_memory_size",u"marshalled_input_size",b"marshalled_input_size",u"number_of_exited_samples",b"number_of_exited_samples",u"operators",b"operators",u"storage_size",b"storage_size"]) -> None: ...
global___LayerProfile = LayerProfile
