# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addnn/serve/proto/scheduler.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from addnn.controller.proto import controller_pb2 as addnn_dot_controller_dot_proto_dot_controller__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='addnn/serve/proto/scheduler.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!addnn/serve/proto/scheduler.proto\x1a\'addnn/controller/proto/controller.proto\"\xed\x01\n\x06Report\x12\x17\n\x0fstart_timestamp\x18\x01 \x01(\x04\x12\x15\n\rend_timestamp\x18\x02 \x01(\x04\x12\x34\n\x05nodes\x18\x03 \x03(\x0b\x32%.addnn.grpc.controller.RegisteredNode\x12\x1d\n\tplacement\x18\x04 \x01(\x0b\x32\n.Placement\x12\x19\n\x11\x65stimated_latency\x18\x05 \x01(\x02\x12\x1c\n\x14\x61\x63tivation_durations\x18\x06 \x03(\r\x12%\n\x0elayer_profiles\x18\x07 \x03(\x0b\x32\r.LayerProfile\"\x1a\n\tPlacement\x12\r\n\x05nodes\x18\x01 \x03(\t\"\xea\x01\n\x0cLayerProfile\x12\r\n\x05\x66lops\x18\x01 \x01(\x04\x12\x16\n\x0ein_memory_size\x18\x02 \x01(\x04\x12\x14\n\x0cstorage_size\x18\x03 \x01(\x04\x12\x1d\n\x15marshalled_input_size\x18\x04 \x01(\x04\x12\x10\n\x08has_exit\x18\x05 \x01(\x08\x12 \n\x18number_of_exited_samples\x18\x06 \x01(\r\x12\x18\n\x10\x65xit_probability\x18\x07 \x01(\x02\x12\x1d\n\x15\x65xecution_probability\x18\x08 \x01(\x02\x12\x11\n\toperators\x18\t \x03(\tb\x06proto3'
  ,
  dependencies=[addnn_dot_controller_dot_proto_dot_controller__pb2.DESCRIPTOR,])




_REPORT = _descriptor.Descriptor(
  name='Report',
  full_name='Report',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_timestamp', full_name='Report.start_timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_timestamp', full_name='Report.end_timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='Report.nodes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='placement', full_name='Report.placement', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='estimated_latency', full_name='Report.estimated_latency', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='activation_durations', full_name='Report.activation_durations', index=5,
      number=6, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='layer_profiles', full_name='Report.layer_profiles', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=316,
)


_PLACEMENT = _descriptor.Descriptor(
  name='Placement',
  full_name='Placement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes', full_name='Placement.nodes', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=344,
)


_LAYERPROFILE = _descriptor.Descriptor(
  name='LayerProfile',
  full_name='LayerProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='flops', full_name='LayerProfile.flops', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='in_memory_size', full_name='LayerProfile.in_memory_size', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='storage_size', full_name='LayerProfile.storage_size', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='marshalled_input_size', full_name='LayerProfile.marshalled_input_size', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='has_exit', full_name='LayerProfile.has_exit', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='number_of_exited_samples', full_name='LayerProfile.number_of_exited_samples', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exit_probability', full_name='LayerProfile.exit_probability', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='execution_probability', full_name='LayerProfile.execution_probability', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operators', full_name='LayerProfile.operators', index=8,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=581,
)

_REPORT.fields_by_name['nodes'].message_type = addnn_dot_controller_dot_proto_dot_controller__pb2._REGISTEREDNODE
_REPORT.fields_by_name['placement'].message_type = _PLACEMENT
_REPORT.fields_by_name['layer_profiles'].message_type = _LAYERPROFILE
DESCRIPTOR.message_types_by_name['Report'] = _REPORT
DESCRIPTOR.message_types_by_name['Placement'] = _PLACEMENT
DESCRIPTOR.message_types_by_name['LayerProfile'] = _LAYERPROFILE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Report = _reflection.GeneratedProtocolMessageType('Report', (_message.Message,), {
  'DESCRIPTOR' : _REPORT,
  '__module__' : 'addnn.serve.proto.scheduler_pb2'
  # @@protoc_insertion_point(class_scope:Report)
  })
_sym_db.RegisterMessage(Report)

Placement = _reflection.GeneratedProtocolMessageType('Placement', (_message.Message,), {
  'DESCRIPTOR' : _PLACEMENT,
  '__module__' : 'addnn.serve.proto.scheduler_pb2'
  # @@protoc_insertion_point(class_scope:Placement)
  })
_sym_db.RegisterMessage(Placement)

LayerProfile = _reflection.GeneratedProtocolMessageType('LayerProfile', (_message.Message,), {
  'DESCRIPTOR' : _LAYERPROFILE,
  '__module__' : 'addnn.serve.proto.scheduler_pb2'
  # @@protoc_insertion_point(class_scope:LayerProfile)
  })
_sym_db.RegisterMessage(LayerProfile)


# @@protoc_insertion_point(module_scope)
