# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addnn/node/proto/neural_network.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='addnn/node/proto/neural_network.proto',
  package='addnn.grpc.neuralnetwork',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n%addnn/node/proto/neural_network.proto\x12\x18\x61\x64\x64nn.grpc.neuralnetwork\"\x1e\n\x0cInferRequest\x12\x0e\n\x06tensor\x18\x01 \x01(\x0c\"W\n\rInferResponse\x12\x16\n\x0e\x63lassification\x18\x01 \x01(\x05\x12\x17\n\x0fstart_timestamp\x18\x02 \x01(\x04\x12\x15\n\rend_timestamp\x18\x03 \x01(\x04\x32k\n\rNeuralNetwork\x12Z\n\x05Infer\x12&.addnn.grpc.neuralnetwork.InferRequest\x1a\'.addnn.grpc.neuralnetwork.InferResponse\"\x00\x62\x06proto3'
)




_INFERREQUEST = _descriptor.Descriptor(
  name='InferRequest',
  full_name='addnn.grpc.neuralnetwork.InferRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tensor', full_name='addnn.grpc.neuralnetwork.InferRequest.tensor', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=97,
)


_INFERRESPONSE = _descriptor.Descriptor(
  name='InferResponse',
  full_name='addnn.grpc.neuralnetwork.InferResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='classification', full_name='addnn.grpc.neuralnetwork.InferResponse.classification', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_timestamp', full_name='addnn.grpc.neuralnetwork.InferResponse.start_timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_timestamp', full_name='addnn.grpc.neuralnetwork.InferResponse.end_timestamp', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=186,
)

DESCRIPTOR.message_types_by_name['InferRequest'] = _INFERREQUEST
DESCRIPTOR.message_types_by_name['InferResponse'] = _INFERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InferRequest = _reflection.GeneratedProtocolMessageType('InferRequest', (_message.Message,), {
  'DESCRIPTOR' : _INFERREQUEST,
  '__module__' : 'addnn.node.proto.neural_network_pb2'
  # @@protoc_insertion_point(class_scope:addnn.grpc.neuralnetwork.InferRequest)
  })
_sym_db.RegisterMessage(InferRequest)

InferResponse = _reflection.GeneratedProtocolMessageType('InferResponse', (_message.Message,), {
  'DESCRIPTOR' : _INFERRESPONSE,
  '__module__' : 'addnn.node.proto.neural_network_pb2'
  # @@protoc_insertion_point(class_scope:addnn.grpc.neuralnetwork.InferResponse)
  })
_sym_db.RegisterMessage(InferResponse)



_NEURALNETWORK = _descriptor.ServiceDescriptor(
  name='NeuralNetwork',
  full_name='addnn.grpc.neuralnetwork.NeuralNetwork',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=188,
  serialized_end=295,
  methods=[
  _descriptor.MethodDescriptor(
    name='Infer',
    full_name='addnn.grpc.neuralnetwork.NeuralNetwork.Infer',
    index=0,
    containing_service=None,
    input_type=_INFERREQUEST,
    output_type=_INFERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NEURALNETWORK)

DESCRIPTOR.services_by_name['NeuralNetwork'] = _NEURALNETWORK

# @@protoc_insertion_point(module_scope)
