"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class InferRequest(google.protobuf.message.Message):
    """Request message of the Infer method of the NeuralNetwork service."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TENSOR_FIELD_NUMBER: builtins.int
    tensor: builtins.bytes = ...
    """A pickled torch.Tensor that represents the classifier of this exit."""

    def __init__(self,
        *,
        tensor : builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"tensor",b"tensor"]) -> None: ...
global___InferRequest = InferRequest

class InferResponse(google.protobuf.message.Message):
    """Response message of the Infer method of the NeuralNetwork service."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CLASSIFICATION_FIELD_NUMBER: builtins.int
    START_TIMESTAMP_FIELD_NUMBER: builtins.int
    END_TIMESTAMP_FIELD_NUMBER: builtins.int
    classification: builtins.int = ...
    """The classification result that was inferred for the input tensor."""

    start_timestamp: builtins.int = ...
    """The time at which the inference was triggered (unix time in micro seconds)."""

    end_timestamp: builtins.int = ...
    """The time at which inference finished (unix time in micro seconds)."""

    def __init__(self,
        *,
        classification : builtins.int = ...,
        start_timestamp : builtins.int = ...,
        end_timestamp : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"classification",b"classification",u"end_timestamp",b"end_timestamp",u"start_timestamp",b"start_timestamp"]) -> None: ...
global___InferResponse = InferResponse
