"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import addnn.controller.proto.controller_pb2
import addnn.node.proto.node_state_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Exit(google.protobuf.message.Message):
    """Represents the exit branch of a ADDNN layer."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CLASSIFIER_FIELD_NUMBER: builtins.int
    CONFIDENCE_THRESHOLD_FIELD_NUMBER: builtins.int
    classifier: builtins.bytes = ...
    """A pickled torch.nn.Module that represents the classifier of this exit."""

    confidence_threshold: builtins.float = ...
    """The confidence threshold of this side exit (a value in the closd interval [0.0, 1.0])."""

    def __init__(self,
        *,
        classifier : builtins.bytes = ...,
        confidence_threshold : builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"classifier",b"classifier",u"confidence_threshold",b"confidence_threshold"]) -> None: ...
global___Exit = Exit

class RemoteLayer(google.protobuf.message.Message):
    """Represents an ADDNN layer at a remote host."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    HOST_FIELD_NUMBER: builtins.int
    PORT_FIELD_NUMBER: builtins.int
    host: typing.Text = ...
    """The host name or IP of the node that hosts the layer."""

    port: builtins.int = ...
    """The port at which layer can be reached."""

    def __init__(self,
        *,
        host : typing.Text = ...,
        port : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"host",b"host",u"port",b"port"]) -> None: ...
global___RemoteLayer = RemoteLayer

class LocalLayer(google.protobuf.message.Message):
    """Repesents an locally available ADDNN layer."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MAIN_BRANCH_FIELD_NUMBER: builtins.int
    EXIT_BRANCH_FIELD_NUMBER: builtins.int
    IS_TORCHSCRIPT_FIELD_NUMBER: builtins.int
    main_branch: builtins.bytes = ...
    """A pickled torch.nn.Module that represents this layer's portion of the DNN's main branch."""

    @property
    def exit_branch(self) -> global___Exit:
        """An optional exit that is placed at this layer, which is either hosted by the current node or remotely."""
        pass
    is_torchscript: builtins.bool = ...
    """Whether the layer's branches are instances of `torch.jit.ScriptModule` instead of `torch.nn.Module`."""

    def __init__(self,
        *,
        main_branch : builtins.bytes = ...,
        exit_branch : typing.Optional[global___Exit] = ...,
        is_torchscript : builtins.bool = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"exit_branch",b"exit_branch"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"exit_branch",b"exit_branch",u"is_torchscript",b"is_torchscript",u"main_branch",b"main_branch"]) -> None: ...
global___LocalLayer = LocalLayer

class Layer(google.protobuf.message.Message):
    """Repesents an ADDNN layer."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    LOCAL_LAYER_FIELD_NUMBER: builtins.int
    REMOTE_LAYER_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    @property
    def local_layer(self) -> global___LocalLayer:
        """The layers that are assigned to the current node."""
        pass
    @property
    def remote_layer(self) -> global___RemoteLayer:
        """The endpoint of the remote model that hosts the upper layers of the DNN."""
        pass
    index: builtins.int = ...
    """The index of the layer that globally identifies its position in the ADDNN."""

    def __init__(self,
        *,
        local_layer : typing.Optional[global___LocalLayer] = ...,
        remote_layer : typing.Optional[global___RemoteLayer] = ...,
        index : builtins.int = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"local_layer",b"local_layer",u"remote_layer",b"remote_layer"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"index",b"index",u"local_layer",b"local_layer",u"remote_layer",b"remote_layer"]) -> None: ...
global___Layer = Layer

class LayerRange(google.protobuf.message.Message):
    """References a range of layers in a model."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    START_INDEX_FIELD_NUMBER: builtins.int
    END_INDEX_FIELD_NUMBER: builtins.int
    start_index: builtins.int = ...
    """The index of the first layer referenced by the range."""

    end_index: builtins.int = ...
    """The index of the last layer referenced by the range."""

    def __init__(self,
        *,
        start_index : builtins.int = ...,
        end_index : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"end_index",b"end_index",u"start_index",b"start_index"]) -> None: ...
global___LayerRange = LayerRange

class ActivateLayersRequest(google.protobuf.message.Message):
    """Request message of the ActivateLayers method of the Node service."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ACTIVE_LAYERS_FIELD_NUMBER: builtins.int
    REMOTE_LAYER_FIELD_NUMBER: builtins.int
    @property
    def active_layers(self) -> global___LayerRange:
        """The range of layers that should be active on this node."""
        pass
    @property
    def remote_layer(self) -> global___RemoteLayer:
        """Determines where to reach the next layer, if existing (i.e. `active_layers.end_index + 1`)."""
        pass
    def __init__(self,
        *,
        active_layers : typing.Optional[global___LayerRange] = ...,
        remote_layer : typing.Optional[global___RemoteLayer] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"active_layers",b"active_layers",u"remote_layer",b"remote_layer"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"active_layers",b"active_layers",u"remote_layer",b"remote_layer"]) -> None: ...
global___ActivateLayersRequest = ActivateLayersRequest

class ReadNodeStateRequest(google.protobuf.message.Message):
    """Request message of the ReadNodeState method of the Node service."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NEIGHBOUR_NODES_FIELD_NUMBER: builtins.int
    @property
    def neighbour_nodes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[addnn.controller.proto.controller_pb2.Node]:
        """The current neighbours of the compute node."""
        pass
    def __init__(self,
        *,
        neighbour_nodes : typing.Optional[typing.Iterable[addnn.controller.proto.controller_pb2.Node]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"neighbour_nodes",b"neighbour_nodes"]) -> None: ...
global___ReadNodeStateRequest = ReadNodeStateRequest

class ReadNodeStateResponse(google.protobuf.message.Message):
    """Response message of the ReadNodeState method of the Node service."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NODE_STATE_FIELD_NUMBER: builtins.int
    @property
    def node_state(self) -> addnn.node.proto.node_state_pb2.NodeState:
        """The current state of the compute node."""
        pass
    def __init__(self,
        *,
        node_state : typing.Optional[addnn.node.proto.node_state_pb2.NodeState] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"node_state",b"node_state"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"node_state",b"node_state"]) -> None: ...
global___ReadNodeStateResponse = ReadNodeStateResponse

class UpdateResourceStateRequest(google.protobuf.message.Message):
    """Request message of the UpdateResourceState method of the Node service."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    RESOURCE_STATE_FIELD_NUMBER: builtins.int
    @property
    def resource_state(self) -> addnn.node.proto.node_state_pb2.ResourceState:
        """The updated resource state of the compute node."""
        pass
    def __init__(self,
        *,
        resource_state : typing.Optional[addnn.node.proto.node_state_pb2.ResourceState] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"resource_state",b"resource_state"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"resource_state",b"resource_state"]) -> None: ...
global___UpdateResourceStateRequest = UpdateResourceStateRequest

class ReadNeighbourNodesResponse(google.protobuf.message.Message):
    """Request message of the ReadNeighbourNodes method of the Node service."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NEIGHBOUR_NODES_FIELD_NUMBER: builtins.int
    @property
    def neighbour_nodes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[addnn.controller.proto.controller_pb2.Node]:
        """The current neighbours of the compute node."""
        pass
    def __init__(self,
        *,
        neighbour_nodes : typing.Optional[typing.Iterable[addnn.controller.proto.controller_pb2.Node]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"neighbour_nodes",b"neighbour_nodes"]) -> None: ...
global___ReadNeighbourNodesResponse = ReadNeighbourNodesResponse
